export const tytSubjects = {
  "Türkçe": [
    "Sözcükte Anlam",
    "Cümlede Anlam",
    "Paragrafta Anlam",
    "Anlatım Biçimleri",
    "Ses Bilgisi",
    "Yazım Kuralları",
    "Noktalama İşaretleri",
    "Sözcükte Yapı",
    "Sözcük Türleri",
    "Edat-Bağlaç-Ünlem",
    "Fiil-Ek Fiil",
    "Fiilimsi",
    "Fiilde Çatı",
    "Deyim ve Atasözü",
    "Cümlenin Öğeleri",
    "Cümle Türleri",
    "Anlatım Bozuklukları"
  ],
  "Matematik": [
    "Temel Kavramlar",
    "Sayı Basamakları",
    "Bölme ve Bölünebilme",
    "EBOB-EKOK",
    "Rasyonel Sayılar-Ondalık Sayılar",
    "Basit Eşitsizlikler",
    "Mutlak Değer",
    "Üslü Sayılar",
    "Köklü Sayılar",
    "Çarpanlara Ayırma",
    "Oran Orantı",
    "Denklem Çözme",
    "Problemler",
    "Kümeler-Kartezyen Çarpımı",
    "Fonksiyonlar",
    "Permütasyon",
    "Kombinasyon",
    "Binom",
    "Olasılık",
    "İstatistik",
    "2. Dereceden Denklemler",
    "Karmaşık Sayılar",
    "Polinomlar",
    "Mantık",
    "Veri Analizi"
  ],
  "Geometri": [
    "Doğruda ve Üçgende Açılar",
    "Üçgende Açı-Kenar Bağıntıları",
    "Üçgende Benzerlik",
    "Üçgende Açıortay-Kenarortay",
    "Dik Üçgen",
    "İkizkenar Üçgen",
    "Eşkenar Üçgen",
    "Üçgende Alan",
    "Çokgenler",
    "Dörtgenler",
    "Yamuk-Paralelkenar",
    "Eşkenar Dörtgen",
    "Dikdörtgen",
    "Kare",
    "Deltoid",
    "Çemberde Açı",
    "Çemberde Uzunluk",
    "Dairenin Çevresi ve Alanı",
    "Doğrunun Analitik İncelenmesi",
    "Çemberin Analitik İncelenmesi",
    "Katı Cisimler"
  ],
  "Tarih": [
    "Tarih Bilimine Giriş",
    "Uygarlığın Doğuşu ve İlk Uygarlıklar",
    "İlk Türk Devletleri",
    "İslam Tarihi ve Uygarlığı",
    "Türk-İslam Devletleri",
    "Türkler'in İslamiyeti Kabulü",
    "Türkiye Tarihi",
    "Beylikten Devlete (1300-1453)",
    "Dünya Gücü: Osmanlı Devleti",
    "Osmanlı Duraklama Dönemi",
    "Gerileme Devri (1699 - 1792)",
    "Arayış Yılları (17. Yüzyıl)",
    "Avrupa ve Osmanlı Devleti (18. Yüzyıl)",
    "En Uzun Yüzyıl (1800-1922)",
    "20. Yüzyıl Başlarında Osmanlı Devleti",
    "XIX. YY Osmanlı Devleti",
    "1. Dünya Savaşı - Milli M. Hazırlık D.",
    "Kurtuluş Savaşında Cepheler",
    "Türk İnkılabı",
    "Atatürkçülük ve Atatürk İlkeleri",
    "Türk Dış Politikası"
  ],
  "Fizik": [
    "Fizik Bilimine Giriş",
    "Madde ve Özellikleri",
    "Kuvvet ve Hareket",
    "İş, Güç ve Enerji",
    "Isı, Sıcaklık ve Genleşme",
    "Basınç",
    "Kaldırma Kuvveti",
    "Elektrik ve Manyetizma",
    "Dalgalar",
    "Optik"
  ],
  "Kimya": [
    "Kimya Bilimi",
    "Atom ve Periyodik Sistem",
    "Kimyasal Türler Arası Etkileşimler",
    "Maddenin Halleri",
    "Doğa ve Kimya",
    "Kimyanın Temel Kanunları ve Hesaplamalar",
    "Karışımlar",
    "Asitler-Bazlar ve Tuzlar",
    "Kimya Her Yerde"
  ],
  "Biyoloji": [
    "Yaşam Bilimi Biyoloji",
    "Hücre",
    "Canlılar Dünyası",
    "Hücre Bölünmeleri ve Üreme",
    "Kalıtımın Genel İlkeleri",
    "Ekosistem Ekolojisi ve G. Çevre Sorunları"
  ],
  "Din Kültürü": [
    "İnsan ve Din (İnanç)",
    "İbadet",
    "Hz. Muhammed'in Hayatı",
    "Vahiy ve Akıl",
    "İslam Düşüncesi ve Yorumu",
    "İslamda Değerler, Sanat ve Laiklik",
    "Yaşayan Dinler"
  ],
  "Felsefe": [
    "Felsefe'nin Alanı",
    "Bilgi Felsefesi",
    "Bilim Felsefesi",
    "Varlık Felsefesi",
    "Ahlak Felsefesi",
    "Siyaset Felsefesi",
    "Sanat Felsefesi",
    "Din Felsefesi"
  ],
  "Coğrafya": [
    "İnsan ve Doğa",
    "Dünya'nın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer ve Sıcaklık",
    "İklimler",
    "Basınç ve Rüzgarlar",
    "Nem, Yağış ve Buharlaşma",
    "İç Kuvvetler / Dış Kuvvetler",
    "Su - Toprak ve Bitkiler",
    "Nüfus-Göç-Yerleşme",
    "Türkiye'nin Yer Şekilleri",
    "Ekonomik Faaliyetler",
    "Bölgeler ve Ülkeler",
    "Uluslararası Ulaşım Hatları",
    "Çevre ve Toplum",
    "Doğal Afetler"
  ]
};

export const aytSubjects = {
  "Edebiyat": [
    "Güzel Sanatlar ve Edebiyat",
    "Metinlerin Sınıflandırılması",
    "Şiir Bilgisi",
    "Edebi Sanatlar",
    "İslamiyet Öncesi Türk Edebiyatı",
    "Geçiş Dönemi Türk Edebiyatı",
    "Halk Edebiyatı",
    "Divan Edebiyatı",
    "Tanzimat Edebiyatı",
    "Servet-i Fünun Edebiyatı",
    "Fecr-i Ati Edebiyatı",
    "Milli Edebiyat",
    "Cumhuriyet Şiiri",
    "Cumhuriyet Romanı",
    "Cumhuriyet Tiyatrosu",
    "Cumhuriyet Öğretici Metinler",
    "Edebiyat Akımları"
  ],
  "Matematik": [
    "Fonksiyonlar",
    "İkinci Dereceden Denklemler",
    "Parabol",
    "Eşitsizlikler",
    "Trigonometri",
    "Logaritma",
    "Diziler",
    "Limit ve Süreklilik",
    "Türev",
    "İntegral",
    "Sayma ve Olasılık"
  ],
  "Geometri": [
    "Çember ve Daire",
    "Doğrunun Analitik İncelenmesi",
    "Çemberin Analitik İncelenmesi",
    "Katı Cisimler",
    "Dönüşümler Geometrisi"
  ],
  "Fizik": [
    "Vektörler",
    "Bağıl Hareket",
    "Newton'ın Hareket Yasaları",
    "Bir Boyutta Sabit İvmeli Hareket",
    "İki Boyutta Hareket",
    "Enerji ve Hareket",
    "İtme ve Çizgisel Momentum",
    "Tork, Denge ve Ağırlık Merkezi",
    "Basit Makineler",
    "Elektriksel Kuvvet, Potansiyel, İş",
    "Düzgün Elektrik Alan, Sığa",
    "Manyetizma",
    "Alternatif Akım ve Transformatörler",
    "Çembersel Hareket",
    "Basit Harmonik Hareket",
    "Dalga Mekaniği",
    "Atom Fiziğine Giriş ve Radyoaktivite",
    "Modern Fizik",
    "Modern Fiziğin Teknolojideki Uygulamaları"
  ],
  "Kimya": [
    "Kuantum Modeli",
    "Periyodik Sistem",
    "Gazlar",
    "Sıvı Çözeltiler",
    "Kimyasal Tepkimelerde Enerji",
    "Kimyasal Tepkimelerde Hız",
    "Kimyasal Denge",
    "Sulu Çözelti Dengeleri",
    "Elektrokimya",
    "Karbon Kimyasına Giriş",
    "Organik Bileşikler",
    "Enerji Kaynakları"
  ],
  "Biyoloji": [
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Duyu Organları",
    "Destek ve Hareket Sistemi",
    "Sindirim Sistemi",
    "Dolaşım Sistemi",
    "Solunum Sistemi",
    "Boşaltım Sistemi",
    "Üreme Sistemi ve Embriyonik Gelişim",
    "Komünite ve Popülasyon Ekolojisi",
    "Genden Proteine",
    "Canlılarda Enerji Dönüşümleri",
    "Bitki Biyolojisi",
    "Canlılar ve Çevre"
  ],
  "Tarih-1": [
    "Tarih Bilimi",
    "Uygarlığın Doğuşu",
    "İlk Türk Devletleri",
    "İslam Tarihi",
    "Türk İslam Devletleri",
    "Türkiye Tarihi",
    "Avrupa Tarihi",
    "Osmanlı Devleti (Kuruluş-Yükselme-Duraklama)",
    "Osmanlı Devleti (Gerileme-Dağılma)",
    "20 Yüzyıl Başlarında Osmanlı",
    "1. Dünya Savaşı",
    "Milli Mücadele Dönemi",
    "İnkılaplar",
    "Atatürkçülük ve Atatürk İlkeleri",
    "Türk Dış Politikası"
  ],
  "Coğrafya-1": [
    "Doğal Çevre ve İnsan",
    "Dünyanın Şekli ve Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer ve Sıcaklık",
    "İklim Elemanları",
    "Yerleşme ve Nüfus",
    "Ekonomik Faaliyetler",
    "Bölgeler",
    "Uluslararası Örgütler",
    "Afetler",
    "Beşeri Sistemler"
  ],
  "Felsefe Grubu": [
    "Felsefeye Giriş",
    "Psikoloji Bilimini Tanıyalım",
    "Psikolojinin Temel Süreçleri",
    "Öğrenme Bellek Düşünme",
    "Sosyolojiye Giriş",
    "Birey ve Toplum",
    "Toplumsal Yapı",
    "Mantığa Giriş",
    "Klasik Mantık",
    "Sembolik Mantık"
  ]
};
